---
title: "Combining Non-Cointegration Tests in R"
subtitle: ""
author: "Jens Klenke, Janine Langerbein, Niklas Mika"
date: " April 17th 2020"
output:
  xaringan::moon_reader:
    css: ["default", "assets/sydney-fonts.css", "assets/sydney.css"]
    self_contained: true # if true, fonts will be stored locally
    seal: true # show a title slide with YAML information
    includes:
      in_header: "assets/mathjax-equation-numbers.html"
    nature:
      beforeInit: ["assets/remark-zoom.js", "https://platform.twitter.com/widgets.js"]
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9' #alternatives '16:9' or '4:3' or others e.g. 13:9
      navigation:
        scroll: false #disable slide transitions by scrolling
---
class: inverse

```{r, include=FALSE, cache=FALSE}
library(RefManageR)
BibOptions(check.entries = FALSE, 
           bib.style = "authoryear", 
           cite.style = 'authoryear', 
           style = "markdown",
           hyperlink = FALSE, 
           dashed = FALSE)
myBib <- ReadBib("assets/example.bib", check = FALSE)

options(htmltools.dir.version = FALSE)
options(servr.daemon = TRUE)
options(servr.interval = 0.5)

#xaringan::inf_mr()

#### required packages ####
source(here::here("01_code/packages/packages.R"))



```

# Structure
 

1. Theory of Non-Cointegration Test
2. Implementation
3. Tutorial 
4. Further work

---
# Implementation

```{r eval = FALSE}
bayerhanck(formula, data, lags = 1, trend = "const", 
           test = "all", crit = 0.05)
```


